/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2020, Christoph Neuhauser
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef RENDERERS_HEXAHEDRALMESHRENDERER_HPP
#define RENDERERS_HEXAHEDRALMESHRENDERER_HPP

#include "Mesh/HexMesh/HexMesh.hpp"
#include "SceneData.hpp"

namespace sgl {
    class TransferFunctionWindow;
}
struct InternalState;
class SettingsMap;

/**
 * Super-class for hexahedral mesh renderers.
 */
class HexahedralMeshRenderer {
public:
    HexahedralMeshRenderer(SceneData &sceneData, sgl::TransferFunctionWindow &transferFunctionWindow)
        : sceneData(sceneData), transferFunctionWindow(transferFunctionWindow) {}
    virtual ~HexahedralMeshRenderer() {}

    /// Returns if the visualization mapping needs to be re-generated.
    inline bool isDirty() { return dirty; }
    /// Returns if the data needs to be re-rendered, but the visualization mapping is valid.
    virtual bool needsReRender() { bool tmp = reRender; reRender = false; return tmp; }
    /// Is the slim internal representation used?
    virtual bool getUsesSlimRepresentation() { return false; }

    /**
     * Re-generates the visualization mapping. Must not call any OpenGL functions, as it may be called from a different
     * thread.
     * @param meshIn The mesh to generate a visualization mapping for.
     * @param isNewMesh Whether a new mesh is loaded or just a new renderer is used.
     */
    virtual void generateVisualizationMapping(HexMeshPtr meshIn, bool isNewMesh) {}

    /**
     * Uploads the visualization mapping generated by @see generateVisualizationMapping to the GPU.
     * @param meshIn The mesh to generate a visualization mapping for.
     * @param isNewMesh Whether a new mesh is loaded or just a new renderer is used.
     */
    virtual void uploadVisualizationMapping(HexMeshPtr meshIn, bool isNewMesh) {}

    /// Removes the old mesh.
    virtual void removeOldMesh() { hexMesh = HexMeshPtr(); }

    /// Renders the object to the scene framebuffer.
    virtual void render()=0;
    /// Renders the GUI. The "dirty" and "reRender" flags might be set depending on the user's actions.
    virtual void renderGui()=0;
    /// Updates the internal logic (called once per frame).
    virtual void update(float dt) {}

    /// Called when the resolution of the application window has changed.
    virtual void onResolutionChanged() {}

    /// Called when the transfer function was changed.
    virtual void onTransferFunctionMapRebuilt() {}

    /// For changing performance measurement modes.
    virtual void setNewState(const InternalState& newState) {}
    virtual void setNewSettings(const SettingsMap& settings) {}

protected:
    SceneData& sceneData;
    sgl::TransferFunctionWindow &transferFunctionWindow;
    HexMeshPtr hexMesh;
    bool dirty = true;
    bool reRender = true;
};

#endif // RENDERERS_HEXAHEDRALMESHRENDERER_HPP